### PR TITLE
Update SWarena.php

### PR DESCRIPTION
**Pull request by ataberkw**
Set gamemode to 0

Also tested on ImagicalMine. If you want, you can add to ImagicalMine plugins.

### CODE REVIEW

**Comment by dries-c** [comment]
if creative player are teleported players will be automatic the defaultgamemode

**Comment by ataberkw** [comment]
Oh my default gamemode was 1. So I need to edit plugin. Why did you set to defaultgamemode?

**Comment by svilex** [comment]
useless

**Comment by ataberkw** [comment]
My default gamemode is creative. So I edited. And thanks for this awesome plugin. Perfectly works on imagicalmine

**Comment by svilex** [comment]
@Heroata Ok, no problem, you're welcome. I just don't want this change , anyone is free to edit this plugin :wink:

**Pull request closed without merging**
