### PR TITLE
also works with tesseract (fully tested)

### PR DESCRIPTION
**Pull request by dries-c**

### CODE REVIEW

**Comment by iDirtniverse** [comment]
Proof(Ed), Tesseract have no problems running the plugin.

**Comment by Driesboy** [comment]
nice ads for your server :)

**Comment by iDirtniverse** [comment]
👀👀

**Comment by InspectorGadget** [comment]
You have to fix when there is a player inside the game, the timer starts and it automatically says "You've won the match"... Anyone know which line or anyone wants to volunteer to fix it? I've no idea in it.. 
Thanks

**Comment by svilex** [comment]
@RTGDaCoder [this](https://github.com/svilex/SkyWars-PocketMine/blob/master/SW/resources/SW_configs.yml#L39) is what you are looking for.

**Comment by InspectorGadget** [comment]
Can u check if it works?

**Comment by iDirtniverse** [comment]
@RTGDaCoder :O Disrespect? If you don't want to use his plugin you don't have to.. this is a free public source boi

**Comment by RTGDaCoder** [comment]
Oh Boi.... I didn't say I don't like it or I don't want to use it! I'm
confirming if the feature works. Those are two different things....

**Comment by jeffreyvarga** [comment]
You say it works on Tesseract, but on my server it doest teleport you to the map when you tap the sign:

**Comment by jeffreyvarga** [comment]
Take that back, just checked and my server is clearsky, please tell me how to fix tjis not be teleported to the world problem, you havebthe best sw plugin.

**Comment by InspectorGadget** [comment]
You mind using the original PMMP Build or Tesseract instead of ClearSky. I think ClearSky has been depreciated.

**Comment by ItsLazer** [comment]
ClearSky is inactive but the japan repo isnt inactive

**Comment by InspectorGadget** [comment]
can you link me?

**Pull request closed without merging**
